version: '3.5'
services:
  Aria2-Pro:
    container_name: aria2-pro
    image: p3terx/aria2-pro
    environment:
      - PUID=1005
      - PGID=1005
      - UMASK_SET=022
      - RPC_SECRET=${RPC_SECRET}
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=Asia/Shanghai
    volumes:
      - ${CONFIG_ROOT}/aria2/aria2-config:/config
      - ${MEDIA_ROOT}/downloads:/downloads
    ports:
      - 6800:6800
      - 6888:6888
      - 6888:6888/udp
    networks:
      - nginx_network      
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m

  AriaNg:
    container_name: ariang
    image: p3terx/ariang
    command: --port 6880 --ipv6
    ports:
      - 6880:6880
    networks:
      - nginx_network    
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m

networks:
  nginx_network:
    name: nginx_network
    external: true
