version: "2.1"
services:
  calibre:
    image: linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1005
      - PGID=1005
      - TZ=Asia/Shanghai
      - PASSWORD= ${PASSWORD}
      - CLI_ARGS= #optional
    volumes:
      - ${CONFIG_ROOT}/calibre/config:/config
    ports:
      # - 8080:8080
      # - 8181:8181
      - 8081:8081
    networks:
      - core_network
    restart: unless-stopped
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1005
      - PGID=1005
      - TZ=Asia/Shanghai
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ${CONFIG_ROOT}/calibre-web/config:/config
      - "${CONFIG_ROOT}/calibre/config/Calibre Library:/books"
    ports:
      - 8083:8083
    networks:
      - core_network
    restart: unless-stopped

networks:
  core_network:
    name: core_network
    external: true
