version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    # ports:
    #   - 3000:3000
    environment:
    #   - PUID=1005
    #   - PGID=1005
      HOMEPAGE_ALLOWED_HOSTS: homepage.halfsugar.tech
    volumes:
      - ${CONFIG_ROOT}/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - nginx_network
    restart: unless-stopped

networks:
  nginx_network:
    name: nginx_network
    external: true
