version: "2.4"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    user: 1005:1005
    environment:
      - PUID=1005
      - PGID=1005
      - TZ=Asia/Shanghai
    networks:
      - nginx_network
    restart: unless-stopped
    volumes:
      - ${CONFIG_ROOT}/prometheus/config:/etc/prometheus
      - ${CONFIG_ROOT}/prometheus/data:/prometheus
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    user: 1005:1005
    environment:
      - PUID=1005
      - PGID=1005
      - TZ=Asia/Shanghai
      - GF_SERVER_ROOT_URL=https://grafana.halfsugar.tech/
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    networks:
      - nginx_network
    restart: unless-stopped
    volumes:
      - ${CONFIG_ROOT}/grafana/data:/var/lib/grafana
  pve-exporter:
    image: prompve/prometheus-pve-exporter
    container_name: pve-exporter
    environment:
      - PUID=1005
      - PGID=1005
      - TZ=Asia/Shanghai
    networks:
      - nginx_network
    restart: unless-stopped
    volumes:
      - ${CONFIG_ROOT}/prometheus/config/pve.yml:/etc/prometheus/pve.yml
      - '/:/host:ro,rslave'
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    environment:
      - PUID=1005
      - PGID=1005
      - TZ=Asia/Shanghai
    command:
      - '--path.rootfs=/host'
    # network_mode: host
    networks:
      - nginx_network
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    environment:
      - PUID=1005
      - PGID=1005
      - TZ=Asia/Shanghai
    networks:
      - nginx_network
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro

networks:
  nginx_network:
    name: nginx_network
    external: true
