version: '3.5'
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1005
      - PGID=1005
      - TZ=Asia/Shanghai
    volumes:
      - ${CONFIG_ROOT}/radarr/data:/config
      - ${MEDIA_ROOT}:/media
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - nginx_network
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1005
      - PGID=1005
      - TZ=Asia/Shanghai # Specify a timezone to use
    volumes:
      - ${CONFIG_ROOT}/sonarr/data:/config
      - ${MEDIA_ROOT}:/media #optional
    ports:
      - 8989:8989/tcp # Web UI
    networks:
      - nginx_network
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1005
      - PGID=1005
      - TZ=Asia/Shanghai
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - ${CONFIG_ROOT}/jackett/data:/config
      - ${CONFIG_ROOT}/jackett/downloads:/downloads
    networks:
      - nginx_network
    ports:
      - 9117:9117
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=1005
      - PGID=1005
      - TZ=Asia/Shanghai
    volumes:
      - ${MEDIA_ROOT}/tv:/tv # Location of your TV Shows
      - ${MEDIA_ROOT}/movie:/movies # Location of your movies
      - ${CONFIG_ROOT}/bazarr/config:/config # Bazarr data
    networks:
      - nginx_network
    ports:
      - 6767:6767/tcp # Allows HTTP access to the internal webserver.
  jellyseerr:
    image: fallenbagel/jellyseerr
    container_name: jellyseerr
    environment:
      - PUID=1005
      - PGID=1005
      - LOG_LEVEL=debug
      - TZ=Asia/Shanghai
    networks:
      - nginx_network
    ports:
      - 5055:5055
    volumes:
      - ${CONFIG_ROOT}/jellyseerr/config:/app/config
    restart: unless-stopped
  flaresolverr:
    image: flaresolverr/flaresolverr
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Asia/Shanghai
    networks:
      - nginx_network
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    environment:
      - PUID=1005
      - PGID=1005
      - TZ=Asia/Shanghai
    volumes:
      - ${CONFIG_ROOT}/prowlarr/data:/config
    networks:
      - nginx_network
    ports:
      - 9696:9696
    restart: unless-stopped
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1005
      - PGID=1005
      - TZ=Asia/Shanghai
    volumes:
      - ${CONFIG_ROOT}/lidarr/data:/config
      - ${MEDIA_ROOT}:/media
    networks:
      - nginx_network
    ports:
      - 8686:8686
    restart: unless-stopped
    

networks:
  nginx_network:
    name: nginx_network
    external: true
    
