version: '3.8'
services:
  termix:
    image: ghcr.io/lukegus/termix:2.5.0
    container_name: termix
    restart: unless-stopped
    environment:
      - PUID=1005
      - PGID=1005
      - TZ=Asia/Shanghai
      - PORT=8080
    # ports:
    #   - "8080:8080"
    volumes:
      - ${CONFIG_ROOT}/termix/data:/app/data
    networks:
      - nginx_network
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.termix.rule=Host(`termix.halfsugar.tech`)"
      - "traefik.http.routers.termix.entrypoints=websecure"
      - "traefik.http.routers.termix.tls.certresolver=letsencrypt"
      - "traefik.http.services.termix.loadbalancer.server.port=8080"

networks:
  nginx_network:
    name: nginx_network
    external: true
  traefik_network:
    name: traefik_network
    external: true
